### ISSUE TITLE
Error in Jacobian Matrix in Softmax Derivative

### ISSUE THREAD

**Issue by Marco-Farruggio** [WateryBird/pybernetics#1]
'pybernetics._Utils.Maths.ActivationFunctions.Derivatives.softmax()':

Error in returned the jacobian matrix:

'''
TypeError: only length-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\farru\desktop_files\Desktop\Module Testing (Finna Kill Myself )\pybernetics-package\testing.py", line 18, in <module>
    training_loop = pb.Training.Loop(sgd_optimizer, dataset, cc_loss, nn_layers, 2000)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\farru\desktop_files\Desktop\Module Testing (Finna Kill Myself )\pybernetics-package\pybernetics\Training.py", line 52, in __init__
    layer.backward(loss_function.dinputs)
  File "c:\Users\farru\desktop_files\Desktop\Module Testing (Finna Kill Myself )\pybernetics-package\pybernetics\Layers.py", line 266, in backward
    self.dinputs = dvalues * _Utils.Maths.ActivationFunctions.Derivatives.softmax(self.inputs)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\farru\desktop_files\Desktop\Module Testing (Finna Kill Myself )\pybernetics-package\pybernetics\_Utils.py", line 221, in softmax
    jacobian_matrix[i][j] = sm[i] * (1 - sm[i])
    ~~~~~~~~~~~~~~~~~~^^^
ValueError: setting an array element with a sequence.
'''

**Comment by Marco-Farruggio** [comment]
Work in progress to fix
